# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 908a9385b2ed353ca442a9ab182eb553653cb25672c9031ccf4b11c80e4545c97d064a894e52844d55314294bf35b095a043791774fdf5eaf26f1db6111dd956

test:
  secret_key_base: ed656a45944f684345f131509b2c8e0a9589a26aea373de57a5afec2f51bf24346c25d77dd0f8d152b796ab58aa01b161960df6ca2a580bd51a309e78fa5f48a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
